[workspace]
channels = ["rapidsai", "conda-forge"]
name = "cudf-example"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]

[system-requirements]
cuda = "12"

[target.linux-64.dependencies]
cudf = ">=25.6.0,<26"
